/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ilpeiris
 */
public class AppointmentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppointmentForm.class.getName());

    /**
     * Creates new form AppointmentForm
     */
    public AppointmentForm() {
        
        
        // BG
        setContentPane(new javax.swing.JPanel() {
           
            java.awt.Image bgImage = new javax.swing.ImageIcon(getClass().getResource("/view/images/wbg.jpg")).getImage();
            
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.drawImage(bgImage, 0, 0, getWidth(), getHeight(), this);
            }
        });
        
        
        initComponents();
        
    

        
        // --- Global Window Settings ---
        //// Centers & Disables resizing the window on the screen
        setTitle("Sunrise Dental Clinic - Appointment Management");
        setLocationRelativeTo(null); 
        setResizable(false);   
        
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/images/logo.png")).getImage());
        
        
        loadDentists();
        loadTable();
        generateNextApptNo();
    
    // Multithreading - live clock using thread and runnable
        Thread clockThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while (true) {
                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("hh:mm:ss a");
                        lblLiveClock.setText("Current Time: " + sdf.format(new java.util.Date()));
                        Thread.sleep(1000); 
                    }
                } catch (InterruptedException e) {
                    System.out.println("Clock Thread Interrupted: " + e.getMessage());
                }
            }
        });
        clockThread.start(); 
    }
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtApptNo = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbDentist = new javax.swing.JComboBox<>();
        cmbTreatment = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        txtDateChooser = new com.toedter.calendar.JDateChooser();
        cmbTime = new javax.swing.JComboBox<>();
        filterDateChooser = new com.toedter.calendar.JDateChooser();
        btnFilterDate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblLiveClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Appointment No:");

        jLabel2.setText("Patient Name:");

        jLabel3.setText("Contact Number:");

        jLabel4.setText("Date (YYYY-MM-DD):");

        jLabel5.setText("Time:");

        jLabel6.setText("Select Dentist:");

        jLabel7.setText("Select Treatment:");

        cmbTreatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Cleaning - LKR 2500.00", "Tooth Extraction - LKR 4000.00", "Root Canal - LKR 15000.00", "Teeth Whitening - LKR 8500.00" }));

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appt No", "Date", "Time", "Patient Name", "Doctor", "Treatment"
            }
        ));
        jScrollPane1.setViewportView(tblAppointments);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel8.setText("Address");

        txtAddress.addActionListener(this::txtAddressActionPerformed);

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        cmbTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00 AM", "09:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM" }));

        btnFilterDate.setText("Filter by Date");
        btnFilterDate.addActionListener(this::btnFilterDateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        lblLiveClock.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnSave)
                                .addGap(79, 79, 79)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(131, 131, 131)
                                .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSearch)
                                        .addGap(86, 86, 86)
                                        .addComponent(filterDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFilterDate)))
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtApptNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                            .addComponent(txtPatientName)
                                            .addComponent(txtContact)
                                            .addComponent(txtAddress)
                                            .addComponent(txtDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(78, 78, 78)
                                .addComponent(btnClear)
                                .addGap(86, 86, 86)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLiveClock)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSearch)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFilterDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addGap(80, 80, 80)
                .addComponent(lblLiveClock)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void loadTable() {
        try {
            dao.AppointmentDAO dao = new dao.AppointmentDAO();
            java.sql.ResultSet rs = dao.getAllAppointments();
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAppointments.getModel();
            
            model.setRowCount(0); 
            
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("appointment_no"),
                    rs.getDate("appt_date"),
                    rs.getString("appt_time"),
                    rs.getString("patient_name"),
                    rs.getString("dentist_name"),   
                    rs.getString("treatment_type")
                });
            }
        } catch (Exception e) {
            System.out.println("Table Load Error: " + e.getMessage());
        }
    }
    
    
    private void loadDentists() {
        cmbDentist.removeAllItems(); 
        String sql = "SELECT id, name FROM dentist";
        try (java.sql.Connection con = db.DBConnection.getInstance();
             java.sql.Statement st = con.createStatement();
             java.sql.ResultSet rs = st.executeQuery(sql)) {
             
            while (rs.next()) {
                
                cmbDentist.addItem(rs.getInt("id") + " - " + rs.getString("name"));
            }
        } catch (Exception e) {
            System.out.println("Load Dentist Error: " + e.getMessage());
        }
    }
    
    
    
    private void generateNextApptNo() {
        dao.AppointmentDAO dao = new dao.AppointmentDAO();
        txtApptNo.setText(dao.getAutoAppointmentNo());
        txtApptNo.setEditable(false); 
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        

        
        
        //Gather the Date from JDateChooser
    java.util.Date selectedDate = txtDateChooser.getDate();
    
    if (selectedDate == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an appointment date!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    // Format the date 4 MySQL
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String dateStr = sdf.format(selectedDate);
    
            
        
    // 1. Gather Input
    String apptNo = txtApptNo.getText().trim();
    String patientName = txtPatientName.getText().trim();
    String contact = txtContact.getText().trim();
    String address = txtAddress.getText().trim(); 
    //String dateStr = txtDate.getText().trim();
    String timeStr = cmbTime.getSelectedItem().toString();
    String selectedTreatment = cmbTreatment.getSelectedItem().toString().split(" - ")[0];
    String selectedDentist = cmbDentist.getSelectedItem().toString();
    

    if (patientName.isEmpty() || contact.isEmpty() || apptNo.isEmpty() || address.isEmpty() || dateStr.isEmpty() || timeStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!patientName.matches("[a-zA-Z\\s]+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Name should contain only letters.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!contact.matches("\\d{10}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Contact must be a valid 10-digit number.", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }


    model.Patient patient = new model.Patient();
    patient.setPatientId("P" + System.currentTimeMillis()); // Generate Patient ID
    patient.setName(patientName);
    patient.setContactNumber(contact);
    patient.setAddress(address); 
    
    
    model.Appointment appt = new model.Appointment();
    appt.setAppointmentNo(apptNo);
    appt.setApptDate(java.sql.Date.valueOf(dateStr));
    appt.setApptTime(timeStr);
    
    
    int dentistId = Integer.parseInt(selectedDentist.split(" ")[0]); 
    appt.setDentistId(dentistId);
    
    
    model.Treatment treatment = pattern.TreatmentFactory.getTreatment(selectedTreatment);
    if (treatment != null) {
        appt.setTreatmentId(Integer.parseInt(treatment.getTreatmentId().replaceAll("[^0-9]", "")));
    }

    // Service Layer
    service.AppointmentService apptService = new service.AppointmentService();
    boolean success = apptService.processRegistration(patient, appt);

    if (success) {
        javax.swing.JOptionPane.showMessageDialog(this, "Appointment Registered Successfully!");
        
        //  Simulating SMS Alert
        System.out.println("=====================================");
        System.out.println(">> SMS ALERT TRIGGERED <<");
        System.out.println("To: " + contact);
        System.out.println("Message: Hello " + patientName + ", your appointment (" + apptNo + ") is confirmed for " + dateStr + " at " + timeStr + ".");
        System.out.println("=====================================\n");

        // Clear ALL fields to prevent accidental double-booking
        txtApptNo.setText(""); 
        txtPatientName.setText(""); 
        txtContact.setText("");
        txtAddress.setText(""); 
        cmbTime.setSelectedIndex(0); 
        txtDateChooser.setDate(null); 
        
        // Refresh the JTable
        loadTable(); 
        generateNextApptNo();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to register. Please check for double-booking.", "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        DashboardForm dashboard = new DashboardForm();
    dashboard.setVisible(true);
    this.dispose();
        
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
        String searchKeyword = txtSearch.getText().trim();
    
    try {
        dao.AppointmentDAO dao = new dao.AppointmentDAO();
        java.sql.ResultSet rs = dao.searchAppointment(searchKeyword); 
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAppointments.getModel();
        
        model.setRowCount(0); 
        
        while (rs != null && rs.next()) {
            model.addRow(new Object[]{
                rs.getString("appointment_no"),
                rs.getDate("appt_date"),
                rs.getString("appt_time"),
                rs.getString("name")
            });
        }
    } catch (Exception e) {
        System.out.println("Search UI Error: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnFilterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterDateActionPerformed


java.util.Date selectedDate = filterDateChooser.getDate();
    if (selectedDate != null) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String dateStr = sdf.format(selectedDate);
        
        try {
            dao.AppointmentDAO dao = new dao.AppointmentDAO();
            java.sql.ResultSet rs = dao.searchAppointmentByDate(dateStr); 
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblAppointments.getModel();
            model.setRowCount(0); 
            
            while (rs != null && rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("appointment_no"), 
                    rs.getDate("appt_date"), 
                    rs.getString("appt_time"),
                    rs.getString("patient_name"), 
                    rs.getString("dentist_name"), 
                    rs.getString("treatment_type")
                });
            }
        } catch (Exception e) { 
            System.out.println(e.getMessage()); 
        }
    } else {
        
        loadTable();
    }

        
        
    }//GEN-LAST:event_btnFilterDateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        //txtApptNo.setText(""); 
        txtPatientName.setText(""); 
        txtContact.setText("");
        txtAddress.setText(""); 
        cmbTime.setSelectedIndex(0); 
        txtDateChooser.setDate(null);
        
        
        txtPatientName.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AppointmentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFilterDate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbDentist;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JComboBox<String> cmbTreatment;
    private com.toedter.calendar.JDateChooser filterDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLiveClock;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtApptNo;
    private javax.swing.JTextField txtContact;
    private com.toedter.calendar.JDateChooser txtDateChooser;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
