/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ilpeiris
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        
        // --- Global Window Settings ---
        //// Centers & Disables resizing the window on the screen
        setTitle("Sunrise Dental Clinic - Dashboard");
        setLocationRelativeTo(null); 
        setResizable(false);    
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/images/logo.png")).getImage());
        
        loadDashboardData();
        
    // Multithreading - live clock using thread and runnable
        Thread clockThread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while (true) {
                        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("hh:mm:ss a");
                        lblLiveClock.setText("Current Time: " + sdf.format(new java.util.Date()));
                        Thread.sleep(1000); // Thread pauses fr 1 sec
                    }
                } catch (InterruptedException e) {
                    System.out.println("Clock Thread Interrupted: " + e.getMessage());
                }
            }
        });
        clockThread.start(); // Start the bg thread
    }
    
    
    
    
    
    
    
    
    
    
    
    
    //load session data and analytics
    private void loadDashboardData() {
        // fetch Session Data
        String currentUser = pattern.UserSession.getInstance().getLoggedInUser();
        String loginTime = pattern.UserSession.getInstance().getLoginTime();
        
        // update the Welcome Label
        if (currentUser != null) {
            lblWelcome.setText("Welcome, " + currentUser + " (Logged in at: " + loginTime + ")");
        } else {
            lblWelcome.setText("Welcome, Guest");
        }

        // fetch Analytics
        dao.DashboardDAO dashboardDAO = new dao.DashboardDAO();
        int totalAppts = dashboardDAO.getTotalAppointments();
        lblTotalAppointments.setText("Today Appointments Booked: " + totalAppts);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAppointments = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblTotalAppointments = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblLiveClock = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAppointments.setText("Manage Appointments");
        btnAppointments.addActionListener(this::btnAppointmentsActionPerformed);

        btnBilling.setText("Billing & Receipts");
        btnBilling.addActionListener(this::btnBillingActionPerformed);

        btnLogout.setText("Exit");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        lblWelcome.setText("jLabel1");

        lblTotalAppointments.setText("jLabel2");

        btnHelp.setText("Help");
        btnHelp.addActionListener(this::btnHelpActionPerformed);

        lblLiveClock.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblTotalAppointments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLiveClock)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(lblTotalAppointments)
                .addGap(18, 18, 18)
                .addComponent(btnAppointments)
                .addGap(18, 18, 18)
                .addComponent(btnBilling)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp)
                    .addComponent(lblLiveClock))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        // TODO add your handling code here:
        
        AppointmentForm apptForm = new AppointmentForm();
        apptForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        // TODO add your handling code here:
        
        BillingForm billForm = new BillingForm();
        billForm.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int response = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to logout?", "Logout", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (response == javax.swing.JOptionPane.YES_OPTION) {
        //clear session
        pattern.UserSession.getInstance().clearSession();
        
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
        
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
    HelpForm help = new HelpForm();
    help.setVisible(true);
    this.dispose();        
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel lblLiveClock;
    private javax.swing.JLabel lblTotalAppointments;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
